apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-Deployment
  labels:
    author: intelliqit
    name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app
  template:
    metadata:
      name: redis-deployment-pod
      labels:
        name: redis-app
        author: intelliqit
    spec:
      containers:
        - name: myredis
          image: redis