apiVersion: v1
kind: Service
metadata:
  name: result-app-Service
  labels:
    author: intelliqit
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-app