apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-Deployment
  labels:
    name: voting-app
    author: intelliqit
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      name: voting-app-pod
    labels:
      name: voting-app
    spec:
      containers:
        - name: my-voting-app
          image: dockersamples/examplevotingapp_vote

